# Generated by Django 6.0.5 on 2026-06-16 06:05

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0002_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ball",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "over_number",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Over number (1-based)"
                    ),
                ),
                (
                    "ball_number_in_over",
                    models.PositiveIntegerField(
                        help_text="Ball number within the over (1-6)"
                    ),
                ),
                (
                    "ball_number_in_innings",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Absolute ball number in the innings"
                    ),
                ),
                ("runs_from_bat", models.PositiveIntegerField(default=0)),
                ("runs_extras", models.PositiveIntegerField(default=0)),
                ("total_runs_on_ball", models.PositiveIntegerField(default=0)),
                (
                    "ball_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("WIDE", "Wide"),
                            ("NO_BALL", "No Ball"),
                            ("BYE", "Bye"),
                            ("LEG_BYE", "Leg Bye"),
                            ("PENALTY", "Penalty"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("is_legal", models.BooleanField(default=True)),
                ("is_boundary", models.BooleanField(default=False)),
                ("is_six", models.BooleanField(default=False)),
                ("is_dot_ball", models.BooleanField(default=False)),
                ("is_maiden_ball", models.BooleanField(default=False)),
                (
                    "extras_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIDE", "Wide"),
                            ("NO_BALL", "No Ball"),
                            ("BYE", "Bye"),
                            ("LEG_BYE", "Leg Bye"),
                            ("PENALTY", "Penalty"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("extras_wide_runs", models.PositiveIntegerField(default=0)),
                ("extras_no_ball_runs", models.PositiveIntegerField(default=0)),
                ("extras_bye_runs", models.PositiveIntegerField(default=0)),
                ("extras_leg_bye_runs", models.PositiveIntegerField(default=0)),
                ("extras_penalty_runs", models.PositiveIntegerField(default=0)),
                ("is_wicket", models.BooleanField(default=False)),
                (
                    "dismissal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOWLED", "Bowled"),
                            ("CAUGHT", "Caught"),
                            ("LBW", "LBW"),
                            ("RUN_OUT", "Run Out"),
                            ("STUMPED", "Stumped"),
                            ("HIT_WICKET", "Hit Wicket"),
                            ("RETIRED_HURT", "Retired Hurt"),
                            ("RETIRED_OUT", "Retired Out"),
                            ("OBSTRUCTING", "Obstructing the Field"),
                            ("HANDLED_BALL", "Handled the Ball"),
                            ("TIMED_OUT", "Timed Out"),
                            ("NOT_OUT", "Not Out"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_run_out_assist", models.BooleanField(default=False)),
                (
                    "commentary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "short_commentary",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "bowled_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_bowled",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "bowler_on_dismissal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wickets_taken",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissals",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "fielder_on_dismissal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissals_fielded",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls",
                        to="tournaments.tournamentmatch",
                    ),
                ),
                (
                    "non_striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_at_non_striker",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_faced",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ball",
                "verbose_name_plural": "Balls",
                "db_table": "scoring_balls",
                "ordering": ["innings", "ball_number_in_innings"],
            },
        ),
        migrations.CreateModel(
            name="Innings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "innings_number",
                    models.PositiveIntegerField(
                        default=1, help_text="1st innings, 2nd innings, etc."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DECLARED", "Declared"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        db_index=True,
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("total_wickets", models.PositiveIntegerField(default=0)),
                ("total_extras", models.PositiveIntegerField(default=0)),
                (
                    "total_overs_bowled",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Overs bowled in decimal format (e.g., 12.3 = 12.3 overs)",
                        max_digits=5,
                    ),
                ),
                (
                    "total_legal_balls",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total legal deliveries bowled (excluding wides/noballs)",
                    ),
                ),
                (
                    "total_balls_bowled",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total deliveries bowled (including wides/noballs)",
                    ),
                ),
                (
                    "run_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "required_runs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Runs needed to win (for 2nd innings)",
                        null=True,
                    ),
                ),
                (
                    "required_overs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Overs remaining (for limited-overs chase)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_runs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target set for the opposing team",
                        null=True,
                    ),
                ),
                ("is_declared", models.BooleanField(default=False)),
                ("is_all_out", models.BooleanField(default=False)),
                (
                    "declared_at_wickets",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "declared_at_runs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "powerplay_overs_remaining",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_innings",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_innings",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="tournaments.tournamentmatch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Innings",
                "verbose_name_plural": "Innings",
                "db_table": "scoring_innings",
                "ordering": ["match", "innings_number"],
            },
        ),
        migrations.CreateModel(
            name="FallOfWicket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "wicket_number",
                    models.PositiveIntegerField(help_text="Which wicket fell (1-10)"),
                ),
                (
                    "team_score_at_wicket",
                    models.PositiveIntegerField(
                        help_text="Team total when wicket fell"
                    ),
                ),
                (
                    "overs_at_wicket",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Over when wicket fell",
                        max_digits=5,
                    ),
                ),
                (
                    "ball_number_in_innings",
                    models.PositiveIntegerField(
                        help_text="Absolute ball number when wicket fell"
                    ),
                ),
                (
                    "partnership_runs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Runs scored in this partnership before wicket",
                    ),
                ),
                (
                    "partnership_balls",
                    models.PositiveIntegerField(
                        default=0, help_text="Balls faced in this partnership"
                    ),
                ),
                (
                    "dismissal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOWLED", "Bowled"),
                            ("CAUGHT", "Caught"),
                            ("LBW", "LBW"),
                            ("RUN_OUT", "Run Out"),
                            ("STUMPED", "Stumped"),
                            ("HIT_WICKET", "Hit Wicket"),
                            ("RETIRED_HURT", "Retired Hurt"),
                            ("RETIRED_OUT", "Retired Out"),
                            ("OBSTRUCTING", "Obstructing the Field"),
                            ("HANDLED_BALL", "Handled the Ball"),
                            ("TIMED_OUT", "Timed Out"),
                            ("NOT_OUT", "Not Out"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "batter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_of_wickets",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wicket_taken_fow",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_of_wickets",
                        to="scoring.innings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fall of Wicket",
                "verbose_name_plural": "Fall of Wickets",
                "db_table": "scoring_fall_of_wickets",
                "ordering": ["innings", "wicket_number"],
            },
        ),
        migrations.CreateModel(
            name="Commentary",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("is_auto_generated", models.BooleanField(default=True)),
                ("is_highlight", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ball",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentary_detail",
                        to="scoring.ball",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaries",
                        to="tournaments.tournamentmatch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaries",
                        to="scoring.innings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary",
                "verbose_name_plural": "Commentaries",
                "db_table": "scoring_commentary",
                "ordering": ["-ball__ball_number_in_innings"],
            },
        ),
        migrations.CreateModel(
            name="BowlerFigures",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "overs_bowled",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                ("maidens", models.PositiveIntegerField(default=0)),
                ("runs_conceded", models.PositiveIntegerField(default=0)),
                ("wickets", models.PositiveIntegerField(default=0)),
                ("wides", models.PositiveIntegerField(default=0)),
                ("no_balls", models.PositiveIntegerField(default=0)),
                ("dots", models.PositiveIntegerField(default=0)),
                ("fours_conceded", models.PositiveIntegerField(default=0)),
                ("sixes_conceded", models.PositiveIntegerField(default=0)),
                (
                    "economy_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("balls_bowled", models.PositiveIntegerField(default=0)),
                ("legal_deliveries", models.PositiveIntegerField(default=0)),
                ("bowling_order", models.PositiveIntegerField(default=1)),
                ("is_bowling", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_figures",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_records",
                        to="scoring.innings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bowler Figures",
                "verbose_name_plural": "Bowler Figures",
                "db_table": "scoring_bowler_figures",
                "ordering": ["innings", "bowling_order"],
            },
        ),
        migrations.CreateModel(
            name="BatterInnings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "batting_position",
                    models.PositiveIntegerField(
                        default=1, help_text="Batting position in the order (1-11)"
                    ),
                ),
                ("is_out", models.BooleanField(default=False)),
                (
                    "dismissal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOWLED", "Bowled"),
                            ("CAUGHT", "Caught"),
                            ("LBW", "LBW"),
                            ("RUN_OUT", "Run Out"),
                            ("STUMPED", "Stumped"),
                            ("HIT_WICKET", "Hit Wicket"),
                            ("RETIRED_HURT", "Retired Hurt"),
                            ("RETIRED_OUT", "Retired Out"),
                            ("OBSTRUCTING", "Obstructing the Field"),
                            ("HANDLED_BALL", "Handled the Ball"),
                            ("TIMED_OUT", "Timed Out"),
                            ("NOT_OUT", "Not Out"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("runs", models.PositiveIntegerField(default=0)),
                ("balls_faced", models.PositiveIntegerField(default=0)),
                ("fours", models.PositiveIntegerField(default=0)),
                ("sixes", models.PositiveIntegerField(default=0)),
                (
                    "strike_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("dot_balls", models.PositiveIntegerField(default=0)),
                (
                    "how_out_description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "batting_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "came_to_crease_at",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Innings ball number when this batter came in",
                        null=True,
                    ),
                ),
                (
                    "dismissed_at",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Innings ball number when this batter was dismissed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batters_dismissed",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "fielder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batters_run_out",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_innings",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_records",
                        to="scoring.innings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batter Innings",
                "verbose_name_plural": "Batter Innings",
                "db_table": "scoring_batter_innings",
                "ordering": ["innings", "batting_position"],
            },
        ),
        migrations.AddField(
            model_name="ball",
            name="innings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balls",
                to="scoring.innings",
            ),
        ),
        migrations.CreateModel(
            name="MatchState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("current_over_number", models.PositiveIntegerField(default=0)),
                ("current_ball_in_over", models.PositiveIntegerField(default=0)),
                ("balls_in_current_over", models.PositiveIntegerField(default=0)),
                ("runs", models.PositiveIntegerField(default=0)),
                ("wickets", models.PositiveIntegerField(default=0)),
                (
                    "overs_bowled",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "run_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("target_runs", models.PositiveIntegerField(blank=True, null=True)),
                ("runs_required", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "required_run_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("balls_remaining", models.PositiveIntegerField(blank=True, null=True)),
                ("recent_balls", models.JSONField(blank=True, default=list)),
                ("is_live", models.BooleanField(default=False)),
                ("has_started", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "batting_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batting_state",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bowling_state",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_bowler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_bowler_state",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "current_innings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_state_for",
                        to="scoring.innings",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_state",
                        to="tournaments.tournamentmatch",
                    ),
                ),
                (
                    "non_striker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="non_striker_state",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="striker_state",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match State",
                "verbose_name_plural": "Match States",
                "db_table": "scoring_match_state",
            },
        ),
        migrations.CreateModel(
            name="OverSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("over_number", models.PositiveIntegerField(db_index=True)),
                ("runs_conceded", models.PositiveIntegerField(default=0)),
                ("wickets_in_over", models.PositiveIntegerField(default=0)),
                ("is_maiden", models.BooleanField(default=False)),
                ("is_wicket_maiden", models.BooleanField(default=False)),
                ("total_balls", models.PositiveIntegerField(default=6)),
                ("legal_balls", models.PositiveIntegerField(default=6)),
                ("extra_balls", models.PositiveIntegerField(default=0)),
                ("runs_from_bat", models.PositiveIntegerField(default=0)),
                ("runs_extras", models.PositiveIntegerField(default=0)),
                ("dot_balls", models.PositiveIntegerField(default=0)),
                ("boundaries", models.PositiveIntegerField(default=0)),
                ("sixes_in_over", models.PositiveIntegerField(default=0)),
                (
                    "cumulative_score",
                    models.PositiveIntegerField(
                        help_text="Team score at end of this over"
                    ),
                ),
                (
                    "cumulative_wickets",
                    models.PositiveIntegerField(
                        help_text="Team wickets at end of this over"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overs_bowled",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="over_summaries",
                        to="scoring.innings",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Over Summary",
                "verbose_name_plural": "Over Summaries",
                "db_table": "scoring_over_summaries",
                "ordering": ["innings", "over_number"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("runs", models.PositiveIntegerField(default=0)),
                ("balls_faced", models.PositiveIntegerField(default=0)),
                ("fours", models.PositiveIntegerField(default=0)),
                ("sixes", models.PositiveIntegerField(default=0)),
                ("is_current", models.BooleanField(default=True)),
                ("start_at_ball", models.PositiveIntegerField()),
                ("end_at_ball", models.PositiveIntegerField(blank=True, null=True)),
                ("ended_by_wicket", models.BooleanField(default=False)),
                (
                    "run_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "batter_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_as_one",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "batter_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_as_two",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="scoring.innings",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnership",
                "verbose_name_plural": "Partnerships",
                "db_table": "scoring_partnerships",
                "ordering": ["-runs"],
            },
        ),
        migrations.AddIndex(
            model_name="innings",
            index=models.Index(
                fields=["match", "batting_team"], name="scoring_inn_match_i_feda96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="innings",
            index=models.Index(
                fields=["match", "status"], name="scoring_inn_match_i_10ce76_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fallofwicket",
            unique_together={("innings", "wicket_number")},
        ),
        migrations.AddIndex(
            model_name="commentary",
            index=models.Index(
                fields=["match", "-created_at"], name="scoring_com_match_i_1ca6c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentary",
            index=models.Index(
                fields=["innings", "-created_at"], name="scoring_com_innings_5cc3d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentary",
            index=models.Index(
                fields=["is_highlight"], name="scoring_com_is_high_14130d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bowlerfigures",
            index=models.Index(
                fields=["innings", "player"], name="scoring_bow_innings_d7e908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bowlerfigures",
            index=models.Index(
                fields=["player", "wickets"], name="scoring_bow_player__057ea0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bowlerfigures",
            constraint=models.UniqueConstraint(
                fields=("innings", "player"), name="unique_bowler_in_innings"
            ),
        ),
        migrations.AddIndex(
            model_name="batterinnings",
            index=models.Index(
                fields=["innings", "player"], name="scoring_bat_innings_5e11f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batterinnings",
            index=models.Index(
                fields=["player", "is_out"], name="scoring_bat_player__ec490f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batterinnings",
            constraint=models.UniqueConstraint(
                fields=("innings", "player"), name="unique_batter_in_innings"
            ),
        ),
        migrations.AddIndex(
            model_name="ball",
            index=models.Index(
                fields=["innings", "over_number", "bowler"],
                name="scoring_bal_innings_47dc22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ball",
            index=models.Index(
                fields=["match", "over_number"], name="scoring_bal_match_i_1d6ccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ball",
            index=models.Index(
                fields=["striker", "innings"], name="scoring_bal_striker_3ec02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ball",
            index=models.Index(
                fields=["bowler", "innings"], name="scoring_bal_bowler__3d2b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ball",
            index=models.Index(
                fields=["is_wicket", "innings"], name="scoring_bal_is_wick_3374e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ball",
            constraint=models.UniqueConstraint(
                fields=("innings", "over_number", "ball_number_in_over"),
                name="unique_ball_in_over",
            ),
        ),
        migrations.AddConstraint(
            model_name="ball",
            constraint=models.UniqueConstraint(
                fields=("innings", "ball_number_in_innings"),
                name="unique_ball_in_innings",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oversummary",
            unique_together={("innings", "over_number")},
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["innings", "is_current"], name="scoring_par_innings_6856db_idx"
            ),
        ),
    ]
