# Generated by Django 6.0.5 on 2026-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_state",
            field=models.CharField(
                choices=[
                    ("GUEST", "Guest"),
                    ("PLAYER_PAYMENT_PENDING", "Player Payment Pending"),
                    ("PLAYER_TRIAL_ELIGIBLE", "Trial Eligible"),
                    ("PLAYER_SELECTED", "Selected Player"),
                ],
                db_index=True,
                default="GUEST",
                max_length=40,
            ),
        ),
    ]
