# Generated by Django 6.0.5 on 2026-06-21 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_organization_plans(apps, schema_editor):
    OrganizationPlan = apps.get_model("accounts", "OrganizationPlan")
    defaults = [
        {
            "name": "Starter",
            "code": "starter",
            "description": "For small academies and trial tournaments.",
            "price": 0,
            "billing_cycle": "FREE",
            "max_tournaments": 1,
            "max_teams": 8,
            "max_players": 120,
            "max_venues": 2,
            "max_users": 5,
            "storage_limit_mb": 500,
            "trial_days": 0,
            "sort_order": 10,
        },
        {
            "name": "Growth",
            "code": "growth",
            "description": "For active organizers running multiple cricket events.",
            "price": 4999,
            "billing_cycle": "MONTHLY",
            "max_tournaments": 5,
            "max_teams": 40,
            "max_players": 800,
            "max_venues": 10,
            "max_users": 25,
            "storage_limit_mb": 5000,
            "trial_days": 14,
            "sort_order": 20,
        },
        {
            "name": "Professional",
            "code": "professional",
            "description": "For leagues, associations and large tournament operators.",
            "price": 14999,
            "billing_cycle": "MONTHLY",
            "max_tournaments": 20,
            "max_teams": 200,
            "max_players": 5000,
            "max_venues": 50,
            "max_users": 100,
            "storage_limit_mb": 25000,
            "trial_days": 14,
            "sort_order": 30,
        },
    ]
    for plan in defaults:
        OrganizationPlan.objects.update_or_create(
            code=plan["code"],
            defaults=plan,
        )


def unseed_organization_plans(apps, schema_editor):
    OrganizationPlan = apps.get_model("accounts", "OrganizationPlan")
    OrganizationPlan.objects.filter(code__in=["starter", "growth", "professional"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_onboarding_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        db_index=True,
                        default="FREE",
                        max_length=20,
                    ),
                ),
                ("max_tournaments", models.PositiveIntegerField(default=1)),
                ("max_teams", models.PositiveIntegerField(default=8)),
                ("max_players", models.PositiveIntegerField(default=120)),
                ("max_venues", models.PositiveIntegerField(default=2)),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("storage_limit_mb", models.PositiveIntegerField(default=500)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Organization Plan",
                "verbose_name_plural": "Organization Plans",
                "ordering": ["sort_order", "price", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "provider",
                    models.CharField(db_index=True, default="RAZORPAY", max_length=20),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=140, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("signature", models.CharField(blank=True, default="", max_length=255)),
                ("is_valid", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Payment Webhook Event",
                "verbose_name_plural": "Payment Webhook Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("organization_name", models.CharField(max_length=180)),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[
                            ("ASSOCIATION", "Association"),
                            ("ACADEMY", "Academy"),
                            ("LEAGUE", "League"),
                            ("TOURNAMENT", "Tournament"),
                            ("FRANCHISE", "Franchise"),
                            ("CORPORATE", "Corporate Organization"),
                        ],
                        default="LEAGUE",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("expected_teams", models.PositiveIntegerField(default=0)),
                ("expected_players", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROVISIONED", "Provisioned"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizer_applications",
                        to="accounts.organizationplan",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_organizer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizer_application",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer Application",
                "verbose_name_plural": "Organizer Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PLAYER_REGISTRATION", "Player Registration"),
                            ("ORGANIZER_PLAN", "Organizer Plan"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("RAZORPAY", "Razorpay")],
                        db_index=True,
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=140, unique=True),
                ),
                (
                    "gateway_order_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("gateway_payload", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "organizer_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_ledger",
                        to="accounts.organizerapplication",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_ledger",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Ledger",
                "verbose_name_plural": "Payment Ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("IN_APP", "In App"),
                        ],
                        db_index=True,
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=180)),
                ("body", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Outbox",
                "verbose_name_plural": "Notification Outbox",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "status"],
                        name="accounts_no_event_t_277cf1_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="accounts_no_channel_ef78ed_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organizerapplication",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_or_status_bdf1f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizerapplication",
            index=models.Index(
                fields=["email", "status"], name="accounts_or_email_8ae3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentledger",
            index=models.Index(
                fields=["purpose", "status"], name="accounts_pa_purpose_fda2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentledger",
            index=models.Index(
                fields=["provider", "gateway_order_id"],
                name="accounts_pa_provide_850218_idx",
            ),
        ),
        migrations.RunPython(seed_organization_plans, unseed_organization_plans),
    ]
