# Generated by Django 6.0.5 on 2026-06-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organizationplan_paymentwebhookevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Trialing"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suspension_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "organizer_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription",
                        to="accounts.organizerapplication",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="accounts.organizationplan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_subscription",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Subscription",
                "verbose_name_plural": "Organization Subscriptions",
                "ordering": ["-current_period_start"],
                "indexes": [
                    models.Index(
                        fields=["status", "current_period_end"],
                        name="accounts_or_status_c5c249_idx",
                    )
                ],
            },
        ),
    ]
