# Generated by Django 6.0.5 on 2026-06-16 05:06

import apps.common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=2026,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "season",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "registration_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("registration_end_date", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("total_teams", models.PositiveIntegerField(default=0)),
                ("total_matches", models.PositiveIntegerField(default=0)),
                ("total_players", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournaments/banners/"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournaments/logos/"
                    ),
                ),
                ("rules_and_regulations", models.TextField(blank=True, default="")),
                (
                    "prize_money",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_teams_allowed",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this tournament.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "db_table": "tournaments",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentAward",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "prize_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("criteria", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_awards",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_award_wins",
                        to="players.playerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Award",
                "verbose_name_plural": "Tournament Awards",
                "db_table": "tournaments_awards",
            },
        ),
        migrations.CreateModel(
            name="TournamentFormat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "max_teams",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum number of teams allowed (0 = unlimited)",
                    ),
                ),
                ("max_players_per_team", models.PositiveIntegerField(default=15)),
                ("allow_draws", models.BooleanField(default=False)),
                (
                    "points_for_win",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
                (
                    "points_for_draw",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "points_for_loss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("has_group_stage", models.BooleanField(default=False)),
                ("has_knockout_stage", models.BooleanField(default=True)),
                (
                    "number_of_legs",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of legs per match (1=single leg, 2=home/away)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Format",
                "verbose_name_plural": "Tournament Formats",
                "db_table": "tournaments_formats",
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_tournaments",
                to="tournaments.tournamentformat",
            ),
        ),
        migrations.CreateModel(
            name="TournamentMedia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Document"),
                            ("OTHER", "Other"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="tournaments/media/")),
                ("caption", models.TextField(blank=True, default="")),
                ("is_featured", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_media",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Media",
                "verbose_name_plural": "Tournament Media",
                "db_table": "tournaments_media",
            },
        ),
        migrations.CreateModel(
            name="TournamentOfficial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("UMPIRE", "Umpire"),
                            ("THIRD_UMPIRE", "Third Umpire"),
                            ("REFEREE", "Match Referee"),
                            ("SCORER", "Scorer"),
                            ("COMMISSIONER", "Tournament Commissioner"),
                            ("OTHER", "Other"),
                        ],
                        default="UMPIRE",
                        max_length=30,
                    ),
                ),
                ("is_chief_official", models.BooleanField(default=False)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assignments",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_officials",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Official",
                "verbose_name_plural": "Tournament Officials",
                "db_table": "tournaments_officials",
            },
        ),
        migrations.CreateModel(
            name="TournamentSponsor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "sponsorship_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournaments/sponsors/"
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_sponsors",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Sponsor",
                "verbose_name_plural": "Tournament Sponsors",
                "db_table": "tournaments_sponsors",
            },
        ),
        migrations.CreateModel(
            name="TournamentStage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_group_stage", models.BooleanField(default=False)),
                ("is_knockout_stage", models.BooleanField(default=False)),
                (
                    "number_of_teams",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of teams that enter this stage"
                    ),
                ),
                (
                    "number_of_groups",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of groups (if group stage)"
                    ),
                ),
                (
                    "teams_qualify_per_group",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Teams that qualify from each group to next stage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_stages",
                        to="tournaments.tournamentformat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Stage",
                "verbose_name_plural": "Tournament Stages",
                "db_table": "tournaments_stages",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TournamentStageInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="tournaments.tournamentstage",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_stages",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Stage Instance",
                "verbose_name_plural": "Tournament Stage Instances",
                "db_table": "tournaments_stage_instances",
                "ordering": ["tournament", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="TournamentGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_groups",
                        to="tournaments.tournamentstageinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Group",
                "verbose_name_plural": "Tournament Groups",
                "db_table": "tournaments_groups",
                "ordering": ["stage_instance", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="TournamentTeam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "jersey_color",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "seed",
                    models.PositiveIntegerField(
                        default=0, help_text="Seeding number for tournament"
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_captain_for",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_teams",
                        to="tournaments.tournamentgroup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tournaments",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_teams",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vice_captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_vice_captain_for",
                        to="players.playerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Team",
                "verbose_name_plural": "Tournament Teams",
                "db_table": "tournaments_teams",
            },
        ),
        migrations.CreateModel(
            name="TournamentPointsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("matches_lost", models.PositiveIntegerField(default=0)),
                ("matches_drawn", models.PositiveIntegerField(default=0)),
                ("matches_tied", models.PositiveIntegerField(default=0)),
                ("matches_no_result", models.PositiveIntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "net_run_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                ("runs_for", models.PositiveIntegerField(default=0)),
                ("runs_against", models.PositiveIntegerField(default=0)),
                (
                    "overs_for",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
                ),
                (
                    "overs_against",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_qualified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_standings",
                        to="tournaments.tournamentgroup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_points",
                        to="tournaments.tournamentteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Points Table",
                "verbose_name_plural": "Tournament Points Tables",
                "db_table": "tournaments_points_table",
                "ordering": ["group", "position"],
            },
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(default=0)),
                (
                    "is_playing",
                    models.BooleanField(
                        default=True, help_text="Currently part of active squad"
                    ),
                ),
                ("is_foreign_player", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role in team for this tournament",
                        max_length=50,
                    ),
                ),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_registrations",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_players",
                        to="tournaments.tournamentteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Player",
                "verbose_name_plural": "Tournament Players",
                "db_table": "tournaments_players",
            },
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("match_date", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("ground", models.CharField(blank=True, default="", max_length=255)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("SUPER_OVER", "Super Over"),
                            ("TIE", "Tie"),
                            ("ABANDONED", "Abandoned"),
                            ("WALKOVER", "Walkover"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("is_draw", models.BooleanField(default=False)),
                (
                    "home_team_score",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "away_team_score",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "home_team_overs",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "away_team_overs",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "match_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Match number in tournament"
                    ),
                ),
                (
                    "leg",
                    models.PositiveIntegerField(
                        default=1, help_text="Which leg (1=first, 2=second, etc.)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_matches",
                        to="tournaments.tournamentgroup",
                    ),
                ),
                (
                    "man_of_the_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_mom_awards",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_matches",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_matches",
                        to="tournaments.tournamentstageinstance",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_away_matches",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_home_matches",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_lost_matches",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_won_matches",
                        to="tournaments.tournamentteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Match",
                "verbose_name_plural": "Tournament Matches",
                "db_table": "tournaments_matches",
                "ordering": ["match_date", "match_number"],
            },
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["tenant", "status"], name="tournaments_tenant__6bc3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["year", "season"], name="tournaments_year_3301f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["status", "start_date"], name="tournaments_status_d1c129_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentofficial",
            unique_together={("tournament", "official", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentstageinstance",
            unique_together={("tournament", "stage")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentteam",
            unique_together={("tournament", "team")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentpointstable",
            unique_together={("group", "team")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentplayer",
            unique_together={("tournament_team", "player")},
        ),
        migrations.AddIndex(
            model_name="tournamentmatch",
            index=models.Index(
                fields=["tournament", "match_date"],
                name="tournaments_tournam_b842ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmatch",
            index=models.Index(
                fields=["tournament", "stage_instance"],
                name="tournaments_tournam_785296_idx",
            ),
        ),
    ]
