# Generated by Django 6.0.5 on 2026-06-18 03:32

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchSetup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("READY", "Ready for scoring"),
                            ("LIVE", "Live"),
                            ("INNINGS_BREAK", "Innings break"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "toss_decision",
                    models.CharField(
                        blank=True,
                        choices=[("BAT", "Bat"), ("BOWL", "Bowl")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("toss_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("setup_locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup",
                        to="tournaments.tournamentmatch",
                    ),
                ),
                (
                    "setup_locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_match_setups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "toss_winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tosses_won",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_match_setup",
            },
        ),
        migrations.CreateModel(
            name="TournamentRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("overs_per_innings", models.PositiveIntegerField(default=20)),
                ("players_per_side", models.PositiveIntegerField(default=11)),
                ("max_squad_size", models.PositiveIntegerField(default=25)),
                ("max_overs_per_bowler", models.PositiveIntegerField(default=4)),
                ("powerplay_overs", models.PositiveIntegerField(default=6)),
                ("max_foreign_players_in_xi", models.PositiveIntegerField(default=4)),
                ("allow_impact_player", models.BooleanField(default=True)),
                ("allow_super_over", models.BooleanField(default=True)),
                ("allow_dls", models.BooleanField(default=True)),
                ("free_hit_after_no_ball", models.BooleanField(default=True)),
                (
                    "points_for_win",
                    models.DecimalField(decimal_places=2, default=2, max_digits=5),
                ),
                (
                    "points_for_tie",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "points_for_no_result",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "points_for_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_rules",
            },
        ),
        migrations.CreateModel(
            name="MatchPlayingXI",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "batting_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_captain", models.BooleanField(default=False)),
                ("is_wicket_keeper", models.BooleanField(default=False)),
                ("is_substitute", models.BooleanField(default=False)),
                ("is_impact_player", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_selections",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "tournament_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_selections",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playing_xi",
                        to="tournaments.matchsetup",
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_match_playing_xi",
                "ordering": ["tournament_team", "is_substitute", "batting_position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setup", "player"), name="unique_player_in_match_setup"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchOfficialAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "duty",
                    models.CharField(
                        choices=[
                            ("UMPIRE", "Umpire"),
                            ("THIRD_UMPIRE", "Third Umpire"),
                            ("REFEREE", "Match Referee"),
                            ("SCORER", "Scorer"),
                            ("COMMISSIONER", "Tournament Commissioner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament_official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_assignments",
                        to="tournaments.tournamentofficial",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_assignments",
                        to="tournaments.matchsetup",
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_match_official_assignments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setup", "tournament_official", "duty"),
                        name="unique_match_official_duty",
                    )
                ],
            },
        ),
    ]
