# Generated by Django 6.0.5 on 2026-06-18 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_matchsetup_tournamentrule_matchplayingxi_and_more"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="ground_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="venues.ground",
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="venue_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="venues.venue",
            ),
        ),
    ]
