# Generated by Django 6.0.5 on 2026-06-16 05:06

import apps.common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerBattingSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "technique",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "attacking_play",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "defensive_play",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "footwork",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "timing",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "shot_selection",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "running_between_wickets",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "spin_playing_ability",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pace_playing_ability",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Batting Skill",
                "verbose_name_plural": "Player Batting Skills",
                "db_table": "players_batting_skill",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerBowlingSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "pace_or_speed",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "accuracy",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "swing",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "seam_movement",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "spin",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "yorker_ability",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "bouncer_ability",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "slower_ball_variation",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "googly_doosra",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "death_bowling",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "field_placement_intelligence",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Bowling Skill",
                "verbose_name_plural": "Player Bowling Skills",
                "db_table": "players_bowling_skill",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerCareerStats",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("innings_batted", models.PositiveIntegerField(default=0)),
                ("not_outs", models.PositiveIntegerField(default=0)),
                ("runs_scored", models.PositiveIntegerField(default=0)),
                ("balls_faced", models.PositiveIntegerField(default=0)),
                ("highest_score", models.PositiveIntegerField(default=0)),
                ("hundreds", models.PositiveIntegerField(default=0)),
                ("fifties", models.PositiveIntegerField(default=0)),
                ("ducks", models.PositiveIntegerField(default=0)),
                ("fours", models.PositiveIntegerField(default=0)),
                ("sixes", models.PositiveIntegerField(default=0)),
                (
                    "batting_average",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "strike_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("balls_bowled", models.PositiveIntegerField(default=0)),
                ("runs_conceded", models.PositiveIntegerField(default=0)),
                ("wickets_taken", models.PositiveIntegerField(default=0)),
                ("best_bowling_wickets", models.PositiveIntegerField(default=0)),
                ("best_bowling_runs", models.PositiveIntegerField(default=0)),
                ("five_wicket_hauls", models.PositiveIntegerField(default=0)),
                ("ten_wicket_hauls", models.PositiveIntegerField(default=0)),
                (
                    "bowling_average",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "economy_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "bowling_strike_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("catches", models.PositiveIntegerField(default=0)),
                ("stumpings", models.PositiveIntegerField(default=0)),
                ("run_outs", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("TEST", "Test"),
                            ("ODI", "ODI"),
                            ("T20", "T20"),
                            ("ALL", "All Formats"),
                        ],
                        db_index=True,
                        default="ALL",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Career Stats",
                "verbose_name_plural": "Player Career Stats",
                "db_table": "players_career_stats",
            },
        ),
        migrations.CreateModel(
            name="PlayerContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("HOLD", "On Hold"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("TRIAL", "Trial"),
                            ("ACADEMY", "Academy"),
                            ("SEASONAL", "Seasonal"),
                            ("MATCH_BASIS", "Match Basis"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("signing_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "annual_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "signing_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "match_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "performance_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("no_of_matches", models.PositiveIntegerField(blank=True, null=True)),
                ("termination_clause", models.TextField(blank=True, default="")),
                ("special_terms", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Contract",
                "verbose_name_plural": "Player Contracts",
                "db_table": "players_contract",
                "ordering": ["-signing_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerFieldingSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "catching",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "throwing",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ground_fielding",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "agility",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wicket_keeping",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Fielding Skill",
                "verbose_name_plural": "Player Fielding Skills",
                "db_table": "players_fielding_skill",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerInjury",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("injury_type", models.CharField(db_index=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                ("body_part", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("injury_date", models.DateField(db_index=True)),
                ("expected_recovery_date", models.DateField(blank=True, null=True)),
                ("actual_recovery_date", models.DateField(blank=True, null=True)),
                ("is_recovered", models.BooleanField(db_index=True, default=False)),
                (
                    "treated_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("treatment_notes", models.TextField(blank=True, default="")),
                ("follow_up_required", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Player Injury",
                "verbose_name_plural": "Player Injuries",
                "db_table": "players_injury",
                "ordering": ["-injury_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("pincode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "country",
                    models.CharField(db_index=True, default="India", max_length=100),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("first_name", models.CharField(db_index=True, max_length=100)),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="players/photos/"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BATTER", "Batter"),
                            ("BOWLER", "Bowler"),
                            ("ALL_ROUNDER", "All Rounder"),
                            ("WICKET_KEEPER", "Wicket Keeper"),
                            ("BATTER_WK", "Batter & Wicket Keeper"),
                            ("BOWLING_AR", "Bowling All Rounder"),
                            ("BATTING_AR", "Batting All Rounder"),
                        ],
                        db_index=True,
                        default="BATTER",
                        max_length=20,
                    ),
                ),
                (
                    "batting_style",
                    models.CharField(
                        choices=[
                            ("RIGHT_HAND", "Right Handed"),
                            ("LEFT_HAND", "Left Handed"),
                        ],
                        default="RIGHT_HAND",
                        max_length=20,
                    ),
                ),
                (
                    "bowling_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RA_FAST", "Right Arm Fast"),
                            ("RA_FAST_MEDIUM", "Right Arm Fast Medium"),
                            ("RA_MEDIUM", "Right Arm Medium"),
                            ("RA_OFF_BREAK", "Right Arm Off Break"),
                            ("RA_LEG_BREAK", "Right Arm Leg Break"),
                            ("LA_FAST", "Left Arm Fast"),
                            ("LA_FAST_MEDIUM", "Left Arm Fast Medium"),
                            ("LA_MEDIUM", "Left Arm Medium"),
                            ("LA_ORTHODOX", "Left Arm Orthodox"),
                            ("LA_CHINAMAN", "Left Arm Chinaman"),
                            ("SLOW_LA", "Slow Left Arm"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("is_bowler", models.BooleanField(default=False)),
                ("is_wicket_keeper", models.BooleanField(default=False)),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("debut_date", models.DateField(blank=True, null=True)),
                (
                    "player_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("INJURED", "Injured"),
                            ("RETIRED", "Retired"),
                            ("SUSPENDED", "Suspended"),
                            ("BANNED", "Banned"),
                            ("DECEASED", "Deceased"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("retirement_date", models.DateField(blank=True, null=True)),
                ("is_retired", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("biography", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Profile",
                "verbose_name_plural": "Player Profiles",
                "db_table": "players_profile",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("HOLD", "On Hold"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("transfer_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("LOAN", "Loan"),
                            ("FREE_AGENT", "Free Agent"),
                            ("AUCTION", "Auction"),
                            ("RELEASE", "Release"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("loan_start_date", models.DateField(blank=True, null=True)),
                ("loan_end_date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Player Transfer",
                "verbose_name_plural": "Player Transfers",
                "db_table": "players_transfer",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("MAN_OF_MATCH", "Man of the Match"),
                            ("MAN_OF_SERIES", "Man of the Series"),
                            ("BEST_BATSMAN", "Best Batsman"),
                            ("BEST_BOWLER", "Best Bowler"),
                            ("BEST_FIELDER", "Best Fielder"),
                            ("CENTURY", "Century"),
                            ("HALF_CENTURY", "Half Century"),
                            ("FIVE_WICKETS", "Five Wicket Haul"),
                            ("HAT_TRICK", "Hat Trick"),
                            ("HIGH_SCORE", "Highest Score"),
                            ("BEST_BOWLING", "Best Bowling Figures"),
                            ("SPECIAL", "Special Achievement"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("achieved_date", models.DateField(db_index=True)),
                ("is_career_achievement", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Achievement",
                "verbose_name_plural": "Player Achievements",
                "db_table": "players_achievement",
                "ordering": ["-achieved_date"],
            },
        ),
    ]
