# Generated by Django 6.0.5 on 2026-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(max_length=180)),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="website/gallery/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Registrations Now Open", max_length=120),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Practice with purpose. Play with passion.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="A professional platform for grassroots cricket talent to register, compete and get discovered."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="website/hero/"),
                ),
                (
                    "primary_button_text",
                    models.CharField(default="Register as Player", max_length=60),
                ),
                (
                    "primary_button_url",
                    models.CharField(default="/accounts/register/", max_length=255),
                ),
                (
                    "secondary_button_text",
                    models.CharField(default="Explore League", max_length=60),
                ),
                (
                    "secondary_button_url",
                    models.CharField(default="/match-center/", max_length=255),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="From local grounds to the big stage", max_length=255
                    ),
                ),
                (
                    "about_description",
                    models.TextField(
                        default="RNT MPL gives serious players a structured pathway through registration, trials, selection and competitive cricket."
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/about/"
                    ),
                ),
                (
                    "registration_title",
                    models.CharField(
                        default="Your cricket journey starts here", max_length=255
                    ),
                ),
                (
                    "registration_description",
                    models.TextField(
                        default="Complete your player profile, pay the registration fee securely and track your trial and selection status from your dashboard."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="website/news/"),
                ),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/testimonials/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="icon-award", max_length=60)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/features/"
                    ),
                ),
                ("link_url", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="RNT MPL", max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        default="Bharat Ka Cricket, Har Player Ka Sapna", max_length=255
                    ),
                ),
                ("announcement", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="website/logo/"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/favicon/"
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("registration_open", models.BooleanField(default=True)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=1499, max_digits=10),
                ),
                (
                    "footer_text",
                    models.CharField(default="All Rights Reserved.", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
    ]
