# Generated by Django 6.0.5 on 2026-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_description",
            field=models.TextField(
                default="RNTMPL gives serious players a structured pathway through registration, trials, selection and competitive cricket."
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_name",
            field=models.CharField(default="RNTMPL", max_length=120),
        ),
    ]
