# Generated by Django 6.0.5 on 2026-06-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0002_alter_homepage_about_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="website/hero/slides/")),
                ("primary_button_text", models.CharField(blank=True, max_length=60)),
                ("primary_button_url", models.CharField(blank=True, max_length=255)),
                ("secondary_button_text", models.CharField(blank=True, max_length=60)),
                ("secondary_button_url", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
