# Generated by Django 6.0.5 on 2026-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0003_heroslide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
