# Generated by Django 6.0.5 on 2026-06-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0004_alter_heroslide_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_point_four",
            field=models.CharField(
                default="Transparent selection journey", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_point_one",
            field=models.CharField(default="Verified player identity", max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_point_three",
            field=models.CharField(
                default="Competitive match exposure", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_point_two",
            field=models.CharField(
                default="Professional trial pathway", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_support_text",
            field=models.TextField(
                default="From local grounds and raw talent to structured trials, professional competition and real recognition—RNTMPL gives every serious cricketer a platform to move forward."
            ),
        ),
    ]
