# Generated by Django 6.0.5 on 2026-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publicsite",
            "0005_homepage_about_point_four_homepage_about_point_one_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Blog & News", max_length=80)),
                (
                    "homepage_title",
                    models.CharField(
                        default="Latest From The Cricket World", max_length=180
                    ),
                ),
                (
                    "homepage_description",
                    models.TextField(
                        default="Player stories, league announcements, trial updates and everything happening across the RNTMPL cricket ecosystem."
                    ),
                ),
                (
                    "view_all_text",
                    models.CharField(default="View All Blogs", max_length=40),
                ),
                (
                    "listing_title",
                    models.CharField(
                        default="Cricket Stories & League Updates", max_length=180
                    ),
                ),
                (
                    "detail_back_text",
                    models.CharField(default="Back to Blogs", max_length=40),
                ),
            ],
            options={
                "verbose_name": "Blog Settings",
                "verbose_name_plural": "Blog Settings",
            },
        ),
    ]
