# Generated by Django 6.0.5 on 2026-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0006_blogsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="listing_banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/blog/banner/"
            ),
        ),
    ]
