# Generated by Django 6.0.5 on 2026-06-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0008_blogimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Contact RNTMPL", max_length=80)),
                (
                    "title",
                    models.CharField(default="Let’s Talk Cricket", max_length=180),
                ),
                (
                    "description",
                    models.TextField(
                        default="Questions about registration, trials, teams, partnerships or league operations? Send us a message and our team will connect with you."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/contact/banner/"
                    ),
                ),
                (
                    "form_title",
                    models.CharField(default="Send Us A Message", max_length=120),
                ),
                (
                    "office_hours",
                    models.CharField(
                        default="Monday to Saturday, 10:00 AM – 6:00 PM", max_length=120
                    ),
                ),
                (
                    "response_time",
                    models.CharField(
                        default="We usually respond within one business day.",
                        max_length=120,
                    ),
                ),
                ("map_embed_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Contact Page Settings",
                "verbose_name_plural": "Contact Page Settings",
            },
        ),
    ]
