# Generated by Django 6.0.5 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0009_contactpagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contact FAQ",
                "verbose_name_plural": "Contact FAQs",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="cta_description",
            field=models.CharField(
                default="Create your verified player profile and take the first step toward trials and competitive cricket.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="cta_title",
            field=models.CharField(
                default="Ready To Start Your Cricket Journey?", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="whatsapp_description",
            field=models.CharField(
                default="Need a quick answer about registration or trials? Connect with us directly on WhatsApp.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="whatsapp_title",
            field=models.CharField(default="Chat With Our Team", max_length=120),
        ),
    ]
