# Generated by Django 6.0.5 on 2026-06-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0010_contactfaq_contactpagesettings_cta_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="RNTMPL Events", max_length=80)),
                (
                    "title",
                    models.CharField(
                        default="Cricket Tournaments & Events", max_length=180
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Explore upcoming tournaments, active competitions and completed RNTMPL cricket events."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/events/banner/"
                    ),
                ),
                (
                    "empty_title",
                    models.CharField(default="No events found", max_length=120),
                ),
                (
                    "empty_description",
                    models.CharField(
                        default="New tournaments and cricket events will be announced soon.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Page Settings",
                "verbose_name_plural": "Event Page Settings",
            },
        ),
    ]
