# Generated by Django 6.0.5 on 2026-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0011_eventpagesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="card_badge_text",
            field=models.CharField(default="RNTMPL News", max_length=40),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="detail_author_label",
            field=models.CharField(default="RNTMPL Editorial", max_length=80),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="detail_category",
            field=models.CharField(default="RNTMPL Cricket", max_length=80),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="detail_cta_button_text",
            field=models.CharField(default="Register As Player", max_length=60),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="detail_cta_title",
            field=models.CharField(
                default="Start Your Cricket Journey With RNTMPL", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="empty_title",
            field=models.CharField(default="No blogs published yet", max_length=120),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="gallery_eyebrow",
            field=models.CharField(default="Inside The Story", max_length=80),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="gallery_title",
            field=models.CharField(default="Photo Gallery", max_length=120),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="read_more_text",
            field=models.CharField(default="Read Update", max_length=40),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="related_eyebrow",
            field=models.CharField(default="Keep Reading", max_length=80),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="related_title",
            field=models.CharField(default="Related Cricket Updates", max_length=120),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="all_statuses_text",
            field=models.CharField(default="All Statuses", max_length=50),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="detail_back_text",
            field=models.CharField(default="All Events", max_length=40),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="featured_badge_text",
            field=models.CharField(default="Featured", max_length=40),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="filter_button_text",
            field=models.CharField(default="Filter", max_length=40),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="fixtures_empty_text",
            field=models.CharField(
                default="Fixtures will be published soon.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="fixtures_eyebrow",
            field=models.CharField(default="Schedule", max_length=80),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="fixtures_title",
            field=models.CharField(default="Fixtures & Results", max_length=120),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="matches_label",
            field=models.CharField(default="Matches", max_length=30),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="overview_eyebrow",
            field=models.CharField(default="Tournament Overview", max_length=80),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="overview_title",
            field=models.CharField(default="Event Information", max_length=120),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="players_label",
            field=models.CharField(default="Players", max_length=30),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="prize_label",
            field=models.CharField(default="Prize Pool", max_length=40),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="reset_button_text",
            field=models.CharField(default="Reset", max_length=40),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="search_placeholder",
            field=models.CharField(default="Search event or city", max_length=100),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="teams_empty_text",
            field=models.CharField(
                default="Teams will be announced soon.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="teams_eyebrow",
            field=models.CharField(default="Participants", max_length=80),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="teams_label",
            field=models.CharField(default="Teams", max_length=30),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="teams_title",
            field=models.CharField(default="Teams", max_length=120),
        ),
        migrations.AddField(
            model_name="eventpagesettings",
            name="view_event_text",
            field=models.CharField(default="View Event", max_length=40),
        ),
    ]
