# Generated by Django 6.0.5 on 2026-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0012_blogsettings_card_badge_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="RNTMPL Moments", max_length=80)),
                ("title", models.CharField(default="Cricket Gallery", max_length=180)),
                (
                    "description",
                    models.TextField(
                        default="Match action, team moments, trials and unforgettable scenes from the RNTMPL cricket journey."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/gallery/banner/"
                    ),
                ),
                (
                    "all_filter_text",
                    models.CharField(default="All Moments", max_length=40),
                ),
                (
                    "empty_title",
                    models.CharField(default="No gallery images found", max_length=120),
                ),
                (
                    "empty_description",
                    models.CharField(
                        default="New cricket moments will be published soon.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Page Settings",
                "verbose_name_plural": "Gallery Page Settings",
            },
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="captured_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("MATCH", "Match Action"),
                    ("TEAM", "Teams"),
                    ("TRIAL", "Trials"),
                    ("EVENT", "Events"),
                    ("BEHIND", "Behind The Scenes"),
                    ("OTHER", "Other"),
                ],
                default="MATCH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="event_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
