# Generated by Django 6.0.5 on 2026-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0013_gallerypagesettings_galleryitem_caption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="RNTMPL Newsroom", max_length=80)),
                (
                    "title",
                    models.CharField(default="Latest Cricket News", max_length=180),
                ),
                (
                    "description",
                    models.TextField(
                        default="Official announcements, tournament updates, player news and important information from RNTMPL."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/news/banner/"
                    ),
                ),
                (
                    "read_more_text",
                    models.CharField(default="Read News", max_length=40),
                ),
                (
                    "empty_title",
                    models.CharField(default="No news published yet", max_length=120),
                ),
                (
                    "detail_back_text",
                    models.CharField(default="Back to News", max_length=40),
                ),
                (
                    "related_title",
                    models.CharField(default="More News", max_length=120),
                ),
            ],
            options={
                "verbose_name": "News Page Settings",
                "verbose_name_plural": "News Page Settings",
            },
        ),
        migrations.AddField(
            model_name="newspost",
            name="content_type",
            field=models.CharField(
                choices=[("BLOG", "Blog"), ("NEWS", "News")],
                db_index=True,
                default="BLOG",
                max_length=10,
            ),
        ),
    ]
