# Generated by Django 6.0.5 on 2026-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0014_newspagesettings_newspost_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=180)),
                ("contact_person", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("SPONSOR", "Sponsor"),
                            ("ACADEMY", "Cricket Academy"),
                            ("VENUE", "Venue Partner"),
                            ("MEDIA", "Media Partner"),
                            ("TECHNOLOGY", "Technology Partner"),
                            ("COMMUNITY", "Community Partner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("is_contacted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Partner Enquiry",
                "verbose_name_plural": "Partner Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Partner With RNTMPL", max_length=80),
                ),
                (
                    "title",
                    models.CharField(
                        default="Build The Future Of Cricket With Us", max_length=180
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Collaborate with RNTMPL as a sponsor, academy, venue, media, technology or community partner."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/partners/banner/"
                    ),
                ),
                (
                    "form_title",
                    models.CharField(
                        default="Start A Partnership Conversation", max_length=120
                    ),
                ),
                (
                    "benefits_title",
                    models.CharField(default="Why Partner With RNTMPL", max_length=120),
                ),
                (
                    "benefit_one",
                    models.CharField(
                        default="Reach an active grassroots cricket audience",
                        max_length=160,
                    ),
                ),
                (
                    "benefit_two",
                    models.CharField(
                        default="Build meaningful player and community engagement",
                        max_length=160,
                    ),
                ),
                (
                    "benefit_three",
                    models.CharField(
                        default="Create measurable event and digital visibility",
                        max_length=160,
                    ),
                ),
                (
                    "benefit_four",
                    models.CharField(
                        default="Collaborate through flexible partnership models",
                        max_length=160,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Page Settings",
                "verbose_name_plural": "Partner Page Settings",
            },
        ),
    ]
