# Generated by Django 6.0.5 on 2026-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0015_partnerenquiry_partnerpagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner FAQ",
                "verbose_name_plural": "Partner FAQs",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("logo", models.ImageField(upload_to="website/partners/logos/")),
                ("website_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="icon-star", max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner Opportunity",
                "verbose_name_plural": "Partner Opportunities",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="partnerpagesettings",
            name="faq_title",
            field=models.CharField(default="Partnership FAQs", max_length=120),
        ),
        migrations.AddField(
            model_name="partnerpagesettings",
            name="opportunities_title",
            field=models.CharField(default="Partnership Opportunities", max_length=120),
        ),
        migrations.AddField(
            model_name="partnerpagesettings",
            name="process_title",
            field=models.CharField(default="How Partnership Works", max_length=120),
        ),
    ]
