# Generated by Django 6.0.5 on 2026-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0016_partnerfaq_partnerlogo_partneropportunity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=180)),
                ("contact_person", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(max_length=120)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("UNDER_1L", "Under ₹1 Lakh"),
                            ("1L_5L", "₹1–5 Lakhs"),
                            ("5L_10L", "₹5–10 Lakhs"),
                            ("10L_PLUS", "₹10 Lakhs+"),
                            ("DISCUSS", "Open to Discussion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objectives", models.TextField()),
                ("is_contacted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sponsor Enquiry",
                "verbose_name_plural": "Sponsor Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SponsorLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("logo", models.ImageField(upload_to="website/sponsors/logos/")),
                ("website_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SponsorPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("short_description", models.CharField(max_length=255)),
                ("features", models.TextField(help_text="Enter one feature per line.")),
                ("badge", models.CharField(blank=True, max_length=40)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SponsorPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Sponsor RNTMPL", max_length=80)),
                (
                    "title",
                    models.CharField(
                        default="Put Your Brand At The Heart Of Cricket", max_length=180
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Connect your brand with players, teams, families and cricket audiences through meaningful RNTMPL sponsorship opportunities."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/sponsors/banner/"
                    ),
                ),
                (
                    "packages_title",
                    models.CharField(default="Sponsorship Packages", max_length=120),
                ),
                (
                    "metrics_title",
                    models.CharField(
                        default="A Platform Built For Visibility", max_length=120
                    ),
                ),
                (
                    "form_title",
                    models.CharField(
                        default="Request A Sponsorship Proposal", max_length=120
                    ),
                ),
                ("audience_metric", models.CharField(default="10K+", max_length=40)),
                (
                    "audience_label",
                    models.CharField(default="Cricket Audience", max_length=80),
                ),
                ("players_metric", models.CharField(default="1K+", max_length=40)),
                (
                    "players_label",
                    models.CharField(default="Player Network", max_length=80),
                ),
                ("events_metric", models.CharField(default="25+", max_length=40)),
                (
                    "events_label",
                    models.CharField(default="Event Opportunities", max_length=80),
                ),
                ("cities_metric", models.CharField(default="10+", max_length=40)),
                (
                    "cities_label",
                    models.CharField(default="Target Cities", max_length=80),
                ),
            ],
            options={
                "verbose_name": "Sponsor Page Settings",
                "verbose_name_plural": "Sponsor Page Settings",
            },
        ),
    ]
