# Generated by Django 6.0.5 on 2026-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0017_sponsorenquiry_sponsorlogo_sponsorpackage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=255)),
                ("icon", models.CharField(default="icon-monitor", max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sponsor Inventory",
                "verbose_name_plural": "Sponsor Inventory",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="sponsorpagesettings",
            name="audience_title",
            field=models.CharField(
                default="Connect With A Cricket-First Audience", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sponsorpagesettings",
            name="inventory_title",
            field=models.CharField(
                default="Where Your Brand Can Appear", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sponsorpagesettings",
            name="process_title",
            field=models.CharField(
                default="From Brief To Brand Activation", max_length=120
            ),
        ),
    ]
