# Generated by Django 6.0.5 on 2026-06-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publicsite",
            "0018_sponsorinventory_sponsorpagesettings_audience_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Careers At RNTMPL", max_length=80),
                ),
                (
                    "title",
                    models.CharField(
                        default="Build Your Career In Cricket", max_length=180
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Join a team working across league operations, media, scoring, technology, partnerships and player experiences."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/careers/banner/"
                    ),
                ),
                (
                    "openings_title",
                    models.CharField(default="Current Opportunities", max_length=120),
                ),
                (
                    "benefits_title",
                    models.CharField(default="Why Work With RNTMPL", max_length=120),
                ),
                (
                    "process_title",
                    models.CharField(default="Our Hiring Process", max_length=120),
                ),
                (
                    "form_title",
                    models.CharField(default="Apply To Join The Team", max_length=120),
                ),
            ],
            options={
                "verbose_name": "Career Page Settings",
                "verbose_name_plural": "Career Page Settings",
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("department", models.CharField(max_length=120)),
                ("location", models.CharField(default="India", max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                            ("FREELANCE", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "requirements",
                    models.TextField(help_text="Enter one requirement per line."),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=100)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("current_role", models.CharField(blank=True, max_length=160)),
                ("linkedin_url", models.URLField(blank=True)),
                ("resume", models.FileField(upload_to="website/careers/resumes/")),
                ("cover_note", models.TextField()),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="publicsite.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
