# Generated by Django 6.0.5 on 2026-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0019_careerpagesettings_jobopening_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="RNTMPL Teams", max_length=80)),
                ("title", models.CharField(default="Meet The Teams", max_length=180)),
                (
                    "description",
                    models.TextField(
                        default="Explore active teams, squads, leadership and competitive records across the RNTMPL cricket ecosystem."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/teams/banner/"
                    ),
                ),
                (
                    "search_placeholder",
                    models.CharField(default="Search team or city", max_length=100),
                ),
                (
                    "all_categories_text",
                    models.CharField(default="All Categories", max_length=50),
                ),
                (
                    "empty_title",
                    models.CharField(default="No teams found", max_length=120),
                ),
                (
                    "empty_description",
                    models.CharField(
                        default="Team profiles will appear here when they are published.",
                        max_length=255,
                    ),
                ),
                (
                    "detail_back_text",
                    models.CharField(default="All Teams", max_length=40),
                ),
                (
                    "squad_title",
                    models.CharField(default="Current Squad", max_length=100),
                ),
                ("staff_title", models.CharField(default="Team Staff", max_length=100)),
                (
                    "achievements_title",
                    models.CharField(default="Achievements", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Team Page Settings",
                "verbose_name_plural": "Team Page Settings",
            },
        ),
    ]
