# Generated by Django 6.0.5 on 2026-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0020_teampagesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("designation", models.CharField(max_length=120)),
                ("bio", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/about/leaders/"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="About RNTMPL", max_length=80)),
                (
                    "title",
                    models.CharField(
                        default="Building A Clear Pathway For Indian Cricket",
                        max_length=180,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="RNTMPL connects ambitious players with verified opportunities, structured competition and professional cricket operations."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/about/banner/"
                    ),
                ),
                ("story_eyebrow", models.CharField(default="Our Story", max_length=80)),
                (
                    "story_title",
                    models.CharField(
                        default="From Local Talent To Competitive Cricket",
                        max_length=180,
                    ),
                ),
                (
                    "story_content",
                    models.TextField(
                        default="We created RNTMPL to make cricket opportunities more organised, accessible and transparent for players, teams and partners across India."
                    ),
                ),
                (
                    "story_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/about/story/"
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=120),
                ),
                (
                    "mission_content",
                    models.TextField(
                        default="To create a trusted cricket ecosystem where talent can register, compete, perform and progress through a transparent pathway."
                    ),
                ),
                (
                    "vision_title",
                    models.CharField(default="Our Vision", max_length=120),
                ),
                (
                    "vision_content",
                    models.TextField(
                        default="To become India’s most dependable platform for grassroots cricket development, competition and opportunity."
                    ),
                ),
                (
                    "values_title",
                    models.CharField(default="What Guides Us", max_length=120),
                ),
                (
                    "milestones_title",
                    models.CharField(default="Our Journey", max_length=120),
                ),
                (
                    "leadership_title",
                    models.CharField(default="Leadership Team", max_length=120),
                ),
                (
                    "teams_title",
                    models.CharField(default="Teams In The Ecosystem", max_length=120),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready To Begin Your Cricket Journey?", max_length=180
                    ),
                ),
                (
                    "cta_description",
                    models.CharField(
                        default="Create your verified profile and take the next step towards organised competitive cricket.",
                        max_length=255,
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Register As Player", max_length=60),
                ),
                (
                    "cta_button_url",
                    models.CharField(default="/register-player/", max_length=255),
                ),
            ],
            options={
                "verbose_name": "About Page Settings",
                "verbose_name_plural": "About Page Settings",
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="icon-check-circle",
                        help_text="Feather icon class, e.g. icon-shield",
                        max_length=50,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
