# Generated by Django 6.0.5 on 2026-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0021_aboutleader_aboutmilestone_aboutpagesettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_designation",
            field=models.CharField(default="Founder & Director", max_length=120),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_eyebrow",
            field=models.CharField(default="Founder", max_length=80),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/about/founder/"
            ),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_message",
            field=models.TextField(
                default="RNTMPL was founded with a commitment to give serious cricketers a structured, transparent and professional pathway to compete and progress."
            ),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="founder_name",
            field=models.CharField(default="RNTMPL Founder", max_length=120),
        ),
    ]
