# Generated by Django 6.0.5 on 2026-06-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0022_aboutpagesettings_founder_designation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Help Centre", max_length=80)),
                (
                    "title",
                    models.CharField(
                        default="Frequently Asked Questions", max_length=180
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Find clear answers about registration, trials, teams, events, payments and the RNTMPL platform."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/faq/banner/"
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(default="Still Need Help?", max_length=160),
                ),
                (
                    "contact_description",
                    models.CharField(
                        default="Our support team can help with registration, trials, payments and platform questions.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Page Settings",
                "verbose_name_plural": "FAQ Page Settings",
            },
        ),
        migrations.CreateModel(
            name="PublicContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("privacy-policy", "Privacy Policy"),
                            ("terms-conditions", "Terms & Conditions"),
                            ("refund-policy", "Refund & Cancellation Policy"),
                            ("disclaimer", "Disclaimer"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="RNTMPL Information", max_length=80),
                ),
                ("title", models.CharField(max_length=180)),
                ("summary", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Use plain text. Separate sections with blank lines."
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/legal/banner/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Public Policy Page",
                "verbose_name_plural": "Public Policy Pages",
                "ordering": ["page_type"],
            },
        ),
        migrations.CreateModel(
            name="PublicFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("TRIALS", "Trials & Selection"),
                            ("PAYMENTS", "Payments"),
                            ("TEAMS", "Teams & Events"),
                            ("ACCOUNT", "Account & Support"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Public FAQ",
                "verbose_name_plural": "Public FAQs",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
