# Generated by Django 6.0.5 on 2026-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0023_faqpagesettings_publiccontentpage_publicfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="default_meta_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="default_meta_title",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="default_share_image",
            field=models.ImageField(blank=True, null=True, upload_to="website/seo/"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="whatsapp_message",
            field=models.CharField(
                default="Hello RNTMPL, I want more information.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="whatsapp_number",
            field=models.CharField(
                default="919229229837",
                help_text="Country code and number only, without + or spaces.",
                max_length=20,
            ),
        ),
    ]
