# Generated by Django 6.0.5 on 2026-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0024_websitesettings_default_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="events_eyebrow",
            field=models.CharField(default="Cricket Calendar", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="events_title",
            field=models.CharField(default="Upcoming Cricket Events", max_length=180),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_eyebrow",
            field=models.CharField(default="RNTMPL Moments", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_title",
            field=models.CharField(default="Cricket In Action", max_length=180),
        ),
        migrations.AddField(
            model_name="homepage",
            name="matches_eyebrow",
            field=models.CharField(default="Match Centre", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="matches_title",
            field=models.CharField(default="Upcoming Fixtures", max_length=180),
        ),
        migrations.AddField(
            model_name="homepage",
            name="opportunities_eyebrow",
            field=models.CharField(default="Work With Us", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="opportunities_title",
            field=models.CharField(
                default="Grow With The Cricket Ecosystem", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pathway_description",
            field=models.TextField(
                default="One structured platform to create your cricket identity, attend verified trials, join teams and build a competitive playing record."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pathway_eyebrow",
            field=models.CharField(default="How RNTMPL Works", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pathway_title",
            field=models.CharField(
                default="Your Journey From Registration To Recognition", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="teams_eyebrow",
            field=models.CharField(default="League Teams", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="teams_title",
            field=models.CharField(default="Meet The Competition", max_length=180),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_eyebrow",
            field=models.CharField(default="Community Voices", max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_title",
            field=models.CharField(default="What People Say", max_length=180),
        ),
    ]
