# Generated by Django 6.0.5 on 2026-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0025_homepage_events_eyebrow_homepage_events_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="brochure_english",
            field=models.FileField(
                blank=True, null=True, upload_to="website/brochures/"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="brochure_hindi",
            field=models.FileField(
                blank=True, null=True, upload_to="website/brochures/"
            ),
        ),
    ]
