# Generated by Django 6.0.5 on 2026-06-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0026_websitesettings_brochure_english_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutMilestone",
        ),
        migrations.RemoveField(
            model_name="aboutpagesettings",
            name="milestones_title",
        ),
        migrations.RemoveField(
            model_name="aboutpagesettings",
            name="story_content",
        ),
        migrations.RemoveField(
            model_name="aboutpagesettings",
            name="story_eyebrow",
        ),
        migrations.RemoveField(
            model_name="aboutpagesettings",
            name="story_image",
        ),
        migrations.RemoveField(
            model_name="aboutpagesettings",
            name="story_title",
        ),
    ]
