# Generated by Django 6.0.5 on 2026-06-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_initial"),
        ("publicsite", "0027_delete_aboutmilestone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRegistrationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("role", models.CharField(blank=True, max_length=20)),
                ("batting_style", models.CharField(blank=True, max_length=20)),
                ("bowling_style", models.CharField(blank=True, max_length=30)),
                ("is_wicket_keeper", models.BooleanField(default=False)),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("playing_experience", models.PositiveSmallIntegerField(default=0)),
                ("academy_or_club", models.CharField(blank=True, max_length=180)),
                ("highest_level", models.CharField(blank=True, max_length=80)),
                ("achievements", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACCOUNT_PENDING", "Account Verification Pending"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAYMENT_SUBMITTED", "Payment Submitted"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("consent_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_application",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Registration Application",
                "verbose_name_plural": "Player Registration Applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
