# Generated by Django 6.0.5 on 2026-06-20 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_existing_player_applications(apps, schema_editor):
    Application = apps.get_model('publicsite', 'PlayerRegistrationApplication')
    User = apps.get_model('accounts', 'User')
    for application in Application.objects.select_related('user').all():
        if application.status == 'PAYMENT_SUBMITTED':
            application.payment_status = 'SUBMITTED'
            onboarding_state = 'PLAYER_PAYMENT_PENDING'
        elif application.status == 'COMPLETED':
            application.payment_status = 'VERIFIED'
            application.trial_status = 'SELECTED'
            onboarding_state = 'PLAYER_SELECTED'
        else:
            application.payment_status = 'PENDING'
            onboarding_state = 'PLAYER_PAYMENT_PENDING'
        application.save(update_fields=['payment_status', 'trial_status'])
        if application.user_id:
            User.objects.filter(pk=application.user_id).update(
                onboarding_state=onboarding_state
            )


def reverse_mapping(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_onboarding_state"),
        ("publicsite", "0028_playerregistrationapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playerregistrationapplication",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PENDING", "Payment Pending"),
                    ("SUBMITTED", "Verification Pending"),
                    ("VERIFIED", "Payment Verified"),
                    ("REJECTED", "Payment Rejected"),
                ],
                db_index=True,
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playerregistrationapplication",
            name="trial_status",
            field=models.CharField(
                choices=[
                    ("LOCKED", "Complete Payment First"),
                    ("ELIGIBLE", "Eligible for Trial"),
                    ("INVITED", "Invited"),
                    ("SCHEDULED", "Scheduled"),
                    ("ATTENDED", "Attended"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Not Selected"),
                    ("WAITLISTED", "Waitlisted"),
                ],
                db_index=True,
                default="LOCKED",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            map_existing_player_applications,
            reverse_mapping,
        ),
        migrations.CreateModel(
            name="PlayerPaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="publicsite.playerregistrationapplication",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_player_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTrialEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("venue", models.CharField(max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_player_trials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_trials",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTrialInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Complete Payment First"),
                            ("ELIGIBLE", "Eligible for Trial"),
                            ("INVITED", "Invited"),
                            ("SCHEDULED", "Scheduled"),
                            ("ATTENDED", "Attended"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Not Selected"),
                            ("WAITLISTED", "Waitlisted"),
                        ],
                        db_index=True,
                        default="INVITED",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("attended_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_invitations",
                        to="publicsite.playerregistrationapplication",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="publicsite.playertrialevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTrialEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batting_score", models.PositiveSmallIntegerField(default=0)),
                ("bowling_score", models.PositiveSmallIntegerField(default=0)),
                ("fielding_score", models.PositiveSmallIntegerField(default=0)),
                ("fitness_score", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("SELECT", "Select"),
                            ("REJECT", "Reject"),
                            ("WAITLIST", "Waitlist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_trial_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="publicsite.playertrialinvitation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playertrialinvitation",
            constraint=models.UniqueConstraint(
                fields=("application", "trial"), name="unique_player_application_trial"
            ),
        ),
    ]
