# Generated by Django 6.0.5 on 2026-06-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicsite", "0029_playerregistrationapplication_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpaymenttransaction",
            name="gateway_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="playerpaymenttransaction",
            name="gateway_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="playerpaymenttransaction",
            name="gateway_payment_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="playerpaymenttransaction",
            name="gateway_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="playerpaymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("RAZORPAY", "Razorpay")],
                db_index=True,
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playerpaymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUBMITTED", "Submitted"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
