# Generated by Django 6.0.5 on 2026-06-16 05:06

import apps.common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Team Categories",
                "db_table": "teams_team_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration Document"),
                            ("CONTRACT", "Contract"),
                            ("AGREEMENT", "Agreement"),
                            ("CERTIFICATE", "Certificate"),
                            ("LICENSE", "License"),
                            ("REPORT", "Report"),
                            ("IDENTITY", "Identity Proof"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="teams/documents/")),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Team Documents",
                "db_table": "teams_team_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("TEST", "Test"),
                            ("ODI", "One Day International"),
                            ("T20", "Twenty20"),
                            ("T10", "Ten10"),
                            ("THE_HUNDRED", "The Hundred"),
                            ("LIST_A", "List A"),
                            ("FIRST_CLASS", "First Class"),
                            ("CLUB", "Club"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField(db_index=True)),
                ("previous_rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("ranking_date", models.DateField(auto_now_add=True)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Team Rankings",
                "db_table": "teams_team_ranking",
                "ordering": ["format", "rank"],
            },
        ),
        migrations.CreateModel(
            name="TeamSeason",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SUMMER", "Summer"),
                            ("WINTER", "Winter"),
                            ("MONSOON", "Monsoon"),
                            ("SPRING", "Spring"),
                            ("AUTUMN", "Autumn"),
                            ("ALL_YEAR", "All Year"),
                        ],
                        default="ALL_YEAR",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                ("coach", models.CharField(blank=True, default="", max_length=255)),
                (
                    "assistant_coach",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("manager", models.CharField(blank=True, default="", max_length=255)),
                ("squad_size", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Team Seasons",
                "db_table": "teams_team_season",
                "ordering": ["-year", "team__name"],
            },
        ),
        migrations.CreateModel(
            name="TeamSponsorship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("sponsor_name", models.CharField(max_length=255)),
                (
                    "sponsor_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="teams/sponsors/"
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("TITLE", "Title Sponsor"),
                            ("KIT", "Kit Sponsor"),
                            ("PRINCIPAL", "Principal Sponsor"),
                            ("ASSOCIATE", "Associate Sponsor"),
                            ("GROUND", "Ground Sponsor"),
                            ("BROADCAST", "Broadcast Partner"),
                            ("DIGITAL", "Digital Partner"),
                            ("OFFICIAL", "Official Partner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Team Sponsorships",
                "db_table": "teams_team_sponsorship",
                "ordering": ["team", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="TeamSquad",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("role", models.CharField(blank=True, default="", max_length=50)),
                ("batting_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "bowling_style",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "batting_style",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("is_wicket_keeper", models.BooleanField(default=False)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("left_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("contract_details", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Team Squads",
                "db_table": "teams_team_squad",
                "ordering": ["team_season", "batting_order", "jersey_number"],
            },
        ),
        migrations.CreateModel(
            name="TeamStaff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("HEAD_COACH", "Head Coach"),
                            ("ASSISTANT_COACH", "Assistant Coach"),
                            ("BOWLING_COACH", "Bowling Coach"),
                            ("BATTING_COACH", "Batting Coach"),
                            ("FIELDING_COACH", "Fielding Coach"),
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("TRAINER", "Trainer"),
                            ("DATA_ANALYST", "Data Analyst"),
                            ("VIDEO_ANALYST", "Video Analyst"),
                            ("TEAM_MANAGER", "Team Manager"),
                            ("MEDICAL_OFFICER", "Medical Officer"),
                            ("MASSAGE_THERAPIST", "Massage Therapist"),
                            ("PSYCHOLOGIST", "Psychologist"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("qualifications", models.TextField(blank=True, default="")),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Team Staff Members",
                "db_table": "teams_team_staff",
                "ordering": ["team_season", "staff_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamStat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("OVERALL", "Overall"),
                            ("SEASON", "Season"),
                            ("TOURNAMENT", "Tournament"),
                            ("HOME", "Home"),
                            ("AWAY", "Away"),
                            ("LAST_10", "Last 10 Matches"),
                            ("LAST_20", "Last 20 Matches"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="OVERALL",
                        max_length=50,
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("matches_lost", models.PositiveIntegerField(default=0)),
                ("matches_tied", models.PositiveIntegerField(default=0)),
                ("matches_drawn", models.PositiveIntegerField(default=0)),
                ("matches_no_result", models.PositiveIntegerField(default=0)),
                (
                    "win_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("total_balls_faced", models.PositiveIntegerField(default=0)),
                ("highest_total", models.PositiveIntegerField(default=0)),
                ("lowest_total", models.PositiveIntegerField(default=0)),
                ("centuries", models.PositiveIntegerField(default=0)),
                ("half_centuries", models.PositiveIntegerField(default=0)),
                ("fours", models.PositiveIntegerField(default=0)),
                ("sixes", models.PositiveIntegerField(default=0)),
                (
                    "run_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_balls_bowled", models.PositiveIntegerField(default=0)),
                ("total_runs_conceded", models.PositiveIntegerField(default=0)),
                ("total_wickets", models.PositiveIntegerField(default=0)),
                (
                    "economy_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "best_bowling_figures",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("five_wicket_hauls", models.PositiveIntegerField(default=0)),
                ("catches", models.PositiveIntegerField(default=0)),
                ("stumpings", models.PositiveIntegerField(default=0)),
                ("run_outs", models.PositiveIntegerField(default=0)),
                ("current_win_streak", models.PositiveIntegerField(default=0)),
                ("current_loss_streak", models.PositiveIntegerField(default=0)),
                ("longest_win_streak", models.PositiveIntegerField(default=0)),
                ("longest_loss_streak", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Team Statistics",
                "db_table": "teams_team_stat",
                "ordering": ["team", "-matches_played"],
            },
        ),
        migrations.CreateModel(
            name="TeamTransfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("LOAN", "Loan"),
                            ("PERMANENT", "Permanent Transfer"),
                            ("FREE_AGENT", "Free Agent Signing"),
                            ("DRAFT", "Draft Pick"),
                            ("PROMOTION", "Promotion from Academy"),
                            ("RELEASE", "Release"),
                            ("RETIREMENT", "Retirement"),
                            ("RECALL", "Recall from Loan"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "contract_duration_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("season", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Team Transfers",
                "db_table": "teams_team_transfer",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Team Types",
                "db_table": "teams_team_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("pincode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "country",
                    models.CharField(db_index=True, default="India", max_length=100),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=2026,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("short_name", models.CharField(blank=True, default="", max_length=10)),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="teams/logos/"),
                ),
                (
                    "jersey_color_primary",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "jersey_color_secondary",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "home_ground",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True, default="")),
                ("social_media_links", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this team.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teams",
                "db_table": "teams_team",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamAchievement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=apps.common.models.generate_uuid,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("achievement_date", models.DateField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("CHAMPIONSHIP", "Championship Winner"),
                            ("RUNNER_UP", "Runner Up"),
                            ("SEMI_FINALIST", "Semi Finalist"),
                            ("QUARTER_FINALIST", "Quarter Finalist"),
                            ("PROMOTION", "Promotion"),
                            ("QUALIFICATION", "Tournament Qualification"),
                            ("RECORD", "Record Achievement"),
                            ("AWARD", "Award"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("season", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="teams/achievements/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_achievements",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Team Achievements",
                "db_table": "teams_team_achievement",
                "ordering": ["-achievement_date"],
            },
        ),
    ]
